name: gradle-release-ci
on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure GPG Key
        run: |
          echo -n "SIGNING_KEY" | base64 --decode > /tmp/keyring.gpg
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: zulu
          cache: "gradle"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assemble publish --no-daemon -Psigning.keyId=${{secrets.SIGNING_KEY_ID}} -Psigning.password= -Psigning.secretKeyRingFile=/tmp/keyring.gpg
        env:
          MAVEN_REPO_USER: ${{ secrets.MAVEN_REPO_USER }}
          MAVEN_REPO_PASS: ${{ secrets.MAVEN_REPO_PASS }}
      - name: Set variables
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "UnifiedMetrics ${{ steps.vars.outputs.version }}"
          files: |
            api/build/libs/*.jar
            platforms/*/build/libs/*(.jar|!(*-dev.jar))
